### ISSUE TITLE
Minor: Initial location incorrect 

### ISSUE THREAD

**Issue by jimmybnguyen** [EZPick/EasyPick#24]
~Currently in Brooklyn, NY, and the map is set to downtown Seattle. I am unable to change the location in the map.~

I would prefer for the marker to be at my current location, rather than a default of Seattle, WA, because it makes it harder for me to creating a meeting away from Seattle, especially in a place I am unfamiliar with 

Step 1: Enter EasyPick while away from downtown Seattle
Step 2: Attempt to set the meeting to your current location
Step 2.1: Fail to find NYC the first time because you're bad at geography 
Step 2.2: Fail to find where your current location in NYC because the city is unfamiliar to you. 
Step 2.3: Look up your current location with Google maps
Step 2.4: Move the market in EasyPick to the same location as the one in Google Maps. 
Step 3: Fill out the rest of the info
Step 4: Submit!

**Comment by zmbc** [comment]
@jimmybnguyen When creating a meeting, we aren't showing you your current location, but allowing you to select where you want the meeting to happen. You should be able to click and drag the map marker to change where the location is. Does dragging the marker not work for you?

**Comment by jimmybnguyen** [comment]
Didn't realize I had to drag the marker, changing this to minor!

**Comment by zmbc** [comment]
This issue is a work of art :rofl:

We'll look into making the user's current location the default.
