### ISSUE TITLE
Major: The Send-Invites page does not have a skip button in order to access the invite link manually. The only option on the page is to input email addresses and click Invite button.  

### ISSUE THREAD

**Issue by Nate-Swanson** [EZPick/EasyPick#25]
Reproduction Steps:
Click link to access main page
Click the Create button
Enter all fields abiding by rules 
Click the Submit button
Get redirected to the invite people page with a ‘Submission complete!” located on the top of the page
Only option on page is to input emails and click the Invite button.

**Comment by zmbc** [comment]
Thanks for the report!

I'm going to reclassify this is as major (which I see you originally did), because there's actually an entire page missing from the current flow because of this issue. This should be fixed soon.
