### ISSUE TITLE
[Major] No verification of email address

### ISSUE THREAD

**Issue by lkhwa** [EZPick/EasyPick#33]
I was able to enter the following into your fields:
<img width="570" alt="screen shot 2017-06-04 at 11 57 24 pm" src="https://cloud.githubusercontent.com/assets/22458294/26773779/9b4fb36c-4981-11e7-9098-608db5b4e7bf.png">

..and get success:
<img width="570" alt="screen shot 2017-06-04 at 11 58 16 pm" src="https://cloud.githubusercontent.com/assets/22458294/26773789/b2274ed8-4981-11e7-897f-44b9ea1e3578.png">

If fields like the meeting duration are checked for accuracy, so should the email. As #31 pointed out, it's important to have email verified so that I can get a confirmation of my meeting.

**Comment by zmbc** [comment]
Good point! It succeeds initially because we don't send an email right away, but later on we'd try to (and fail). Definitely a good idea to catch this earlier.
