### ISSUE TITLE
submission failed

### ISSUE THREAD

**Issue by yipang** [EZPick/EasyPick#44]
I cannot create a meeting. Everytime I click on the "submit your meeting" button, it tells me submission failed. However, it doesn't tell me what went wrong...

**Comment by zmbc** [comment]
Thanks for the report! Unfortunately, I'm not able to reproduce the issue with the information you've given. Maybe it's related to your browser version or the platform you're on--would you mind sharing those?

**Comment by yipang** [comment]
I used chrome.

**Comment by zmbc** [comment]
What version of Chrome? What operating system are you on? Have you tried in an incognito window (to eliminate potential problems with extensions or settings)?

**Comment by zmbc** [comment]
Closing as wontfix, because we simply don't have enough information to reproduce this failure. Feel free to reopen with more information.
