### ISSUE TITLE
[Major]: EasyPick isn't displaying my invited guests on the event page

### ISSUE THREAD

**Issue by luisnaranjo733** [EZPick/EasyPick#46]
Here are the steps for reproducing the bug

1. Create a new meeting
2. After getting the green "submission complete" verification message from EasyPick, the web page at http://ezpick.herokuapp.com/create offers to invite people to the meeting by providing their email addresses (separated by commas).
3. Add email addresses and press invite (I only entered one email). 
4. Press "invite"
5. The email address you've added to the input bar disappears, but other than that there is no confirmation that the individual was invited (this is a separate minor issue)
6. The individual does receive the email (I used another one of my emails).
7. On the event page, there is supposed to be a list of all of the invited individuals, but none of the individuals I had invited show up at the event page as advertised (at http://ezpick.herokuapp.com/meeting/62)

**Comment by zmbc** [comment]
Thanks for the report! I can reproduce this.

**Comment by zmbc** [comment]
Fixed in #51.

**Comment by bxie** [comment]
could not verify fix b/c of 500 error when I tried to email invite to somebody
